channel_sources:
  - minrk/label/fenics-windows,conda-forge
c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]

mpi:
  - mpich  # [not win]
  - openmpi  # [not win]
  - impi  # [win]

scalar:
  - real  # [not win]
  - complex  # [not win]

pin_run_as_build:
  parmetis:
    max_pin: x.x
  fenics-ufcx:
    max_pin: x.x.x
