mpi:
  - mpich
  - openmpi

scalar:
  - real
  - complex

c_compiler_version:
  - 15  # [osx]
cxx_compiler_version:
  - 15  # [osx]

pin_run_as_build:
  parmetis:
    max_pin: x.x
  pybind11:
    max_pin: x.x.x
  fenics-ufcx:
    max_pin: x.x.x
