c_stdlib_version:       # [osx and x86]
  - '10.13'             # [osx and x86]
mpi:
  - mpich
  - openmpi

scalar:
  - real
  - complex

pin_run_as_build:
  parmetis:
    max_pin: x.x
  fenics-ufcx:
    max_pin: x.x.x
