c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]

mpi:
  - mpich  # [not win]
  - openmpi  # [not win]
  - impi  # [win]

scalar:
  - real  # [not win]
  - complex  # [not win]

# FIXME: weird mpi crashes in #89
# due to something in intel mpi update
# from 2012.12 to 2012.13
impi:
  - "2021.12"  # [win]
