c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]

mpi:
  - mpich  # [not win]
  - openmpi  # [not win]
  - impi  # [win]

scalar:
  - real  # [not win]
  - complex  # [not win]

hdf5:
  # FIXME: weird mpi crashes in #89
  # due to something in intel mpi update
  - 1.14.3  # [win]

pin_run_as_build:
  parmetis:
    max_pin: x.x
  fenics-ufcx:
    max_pin: x.x.x
