{% set name = "fenics-dolfinx" %}
{% set version = "0.4.1" %}
{% set extra = "" %}
package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/fenics/dolfinx/archive/refs/tags/v{{ version }}{{ extra }}.tar.gz
  sha256: 68dcf29a26c750fcea5e02d8d58411e3b054313c3bf6fcbc1d0f08dd2851117f
  patches:
    - "0001-cpp-test-remove-extra-semicolon.patch"
    - "no-parallel-python-cmake.patch"  # [ target_platform == "linux-aarch64" or target_platform == "linux-ppc64le" ]
    - "cmake-args-python.patch"  # [ target_platform != build_platform ]
build:
  number: 6
  skip: true  # [win]
  script_env:
    - OMPI_ALLOW_RUN_AS_ROOT=1
    - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - OMPI_MCA_rmaps_base_oversubscribe=1
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_btl_vader_single_copy_mechanism=none

requirements:
  build:
    - python  # not used, just for build matrix

outputs:
  - name: fenics-libdolfinx
    script: build-libdolfinx.sh
    build:
      skip_compile_pyc:
        - "*"  # [build_platform != target_platform]
      run_exports:
        - {{ pin_subpackage("fenics-libdolfinx", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - make
        - pkg-config
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - adios2
        - adios2 * mpi_{{ mpi }}_*
        - boost-cpp
        - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
        - parmetis
        - ptscotch
        - petsc
        - slepc
        - xtensor
        - fenics-libbasix 0.4.*
        - fenics-ufcx 0.4.*
      run:
        # host dependencies with run_exports
        - {{ mpi }}
        - hdf5
        - ptscotch
        - petsc
        - slepc
        - fenics-libbasix
        # these don't have run_exports
        # but are needed at runtime for code generation
        - fenics-ufcx
        - boost-cpp
        - parmetis
        - xtensor
    test:
      script: test-libdolfinx.sh
      source_files:
        - cpp/test
      requires:
        - {{ compiler("cxx") }}
        - pkg-config
        - cmake
        - catch2 2.*
        - make
        - fenics-ffcx ==0.4.*,>=0.4.2
  - name: fenics-dolfinx
    script: build-dolfinx.sh
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - make
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - boost-cpp
        # hdf5 shouldn't be needed here, but solver fails without it
        - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
        - {{ pin_subpackage("fenics-libdolfinx", exact=True) }}
        - python
        - pip
        - setuptools >=58
        - wheel
        - pybind11
        - xtensor
        - mpi4py
        - petsc
        - petsc4py
        - slepc
        - slepc4py
      run:
        - {{ compiler("cxx") }}  # [linux]
        - python
        - {{ pin_subpackage("fenics-libdolfinx", exact=True) }}
        - mpi4py
        - numpy
        - petsc4py
        - slepc4py
        - fenics-basix ==0.4.*,>=0.4.1
        - fenics-ffcx ==0.4.*,>=0.4.2
        - fenics-ufl ==2022.1.*
    test:
      script: test-dolfinx.sh
      source_files:
        - python/demo
      requires:
        - pip
        - pytest >=6

about:
  home: https://fenicsproject.org
  summary: The computational environment of FEniCSx
  description: |
    DOLFINx is the computational environment of FEniCSx
    and implements the FEniCS Problem Solving Environment in Python and C++.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://docs.fenicsproject.org/dolfinx/v{{ version }}/
  dev_url: https://github.com/fenics/dolfinx

extra:
  feedstock-name: fenics-dolfinx
  recipe-maintainers:
    - minrk
