{% set name = "fenics-dolfinx" %}
{% set version = "0.6.0" %}
{% set extra = "" %}

# pins are usually updated on minor bumps:
# basix is currently co-versioned with ffcx
{% set major_minor = version.rsplit(".", 1)[0] %}
{% set ufl_version = "2023.1" %}

{% set build = 3 %}
{% if scalar == "real" %}
{%   set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/fenics/dolfinx/archive/refs/tags/v{{ version }}{{ extra }}.tar.gz
  sha256: eb8ac2bb2f032b0d393977993e1ab6b4101a84d54023a67206e3eac1a8d79b80
build:
  number: {{ build }}
  skip: true  # [win or py==37]
  script_env:
    - OMPI_ALLOW_RUN_AS_ROOT=1
    - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - OMPI_MCA_rmaps_base_oversubscribe=1
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_btl_vader_single_copy_mechanism=none

outputs:
  - name: fenics-libdolfinx
    script: build-libdolfinx.sh
    build:
      skip_compile_pyc:
        - '*'  # [build_platform != target_platform]
      run_exports:
        - {{ pin_subpackage("fenics-libdolfinx", max_pin="x.x.x") }}
        - petsc * {{ scalar }}_*
      ignore_run_exports:
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      force_use_keys:
        - python
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - make
        - pkg-config
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
        # python is unconditionally used to check for basix
        # even if it doesn't find it, dolfinx doesn't handle python itself being unavailable
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - {{ mpi }}
        - libadios2
        - libadios2 * mpi_{{ mpi }}_*
        - boost-cpp
        - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
        - parmetis
        - ptscotch
        - petsc
        - petsc * {{ scalar }}_*
        - pugixml
        - slepc
        - fenics-libbasix {{ major_minor }}.*
        - fenics-ufcx {{ major_minor }}.*
      run:
        # host dependencies with run_exports
        - {{ mpi }}
        - hdf5
        - ptscotch
        - petsc * {{ scalar }}_*
        - slepc
        - fenics-libbasix
        # these don't have run_exports
        # but are needed at runtime for code generation
        - fenics-ufcx
        - boost-cpp
        - parmetis
    test:
      script: test-libdolfinx.sh
      source_files:
        - cpp/test
      requires:
        - {{ compiler("cxx") }}
        - pkg-config
        - cmake
        - catch2 2.*
        - make
        - fenics-ffcx {{ major_minor }}.*
  - name: fenics-dolfinx
    script: build-dolfinx.sh
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - make
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - boost-cpp
        # hdf5 shouldn't be needed here, but solver fails without it
        - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
        - {{ pin_subpackage("fenics-libdolfinx", exact=True) }}
        - python
        - pip
        - setuptools >=58
        - wheel
        - pybind11
        - mpi4py
        - petsc * {{ scalar }}_*
        - petsc4py
        - slepc
        - slepc4py
      run:
        # remove version pin from runtime compiler dep
        # we need _a_ compiler, we don't want version pinning
        - {{ compiler("cxx").split()[0] }}  # [linux]
        - pkg-config
        - python
        - {{ pin_subpackage("fenics-libdolfinx", exact=True) }}
        - cffi
        - mpi4py
        - numpy
        - petsc4py
        - slepc4py
        - fenics-basix {{ major_minor }}.*
        - fenics-ffcx {{ major_minor }}.*
        - fenics-ufl {{ ufl_version }}.*
    test:
      script: test-dolfinx.sh
      files:
        - test_dolfinx.py
      source_files:
        - python/demo
      requires:
        - pip
        - pytest >=6

about:
  home: https://fenicsproject.org
  summary: The computational environment of FEniCSx
  description: |
    DOLFINx is the computational environment of FEniCSx
    and implements the FEniCS Problem Solving Environment in Python and C++.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://docs.fenicsproject.org/dolfinx/v{{ version }}/
  dev_url: https://github.com/fenics/dolfinx

extra:
  feedstock-name: fenics-dolfinx
  recipe-maintainers:
    - minrk
