{% set name = "fenics-dolfinx" %}
{% set version = "0.9.0.dev" %}
{% set extra = "" %}

# pins are usually updated on minor bumps:
# basix is currently co-versioned with ffcx
{% set major_minor = version.rsplit(".", 1)[0] %}
{% set ufl_version = "2024.1" %}

{% set build = 0 %}

{%- if scalar is not defined %}
{%- set scalar = "" %}
{%- endif %}

{% if scalar == "real" %}
{%   set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  # url: https://github.com/fenics/dolfinx/archive/refs/tags/v{{ version }}{{ extra }}.tar.gz
  # sha256: acf3104d9ecc0380677a6faf69eabfafc58d0cce43f7777e1307b95701c7cad9
  url: https://github.com/fenics/dolfinx/archive/jhale/windows-build.tar.gz
  patches:
    - findscotch.patch
  #   - unused-variable.patch
  #   - 3180.patch
  #   - 3190.patch

build:
  number: {{ build }}
  skip: true  # [py<39 or not win]
  script_env:
    - OMPI_ALLOW_RUN_AS_ROOT=1
    - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - OMPI_MCA_rmaps_base_oversubscribe=1
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_btl=tcp,self
    - OMPI_MCA_btl_vader_single_copy_mechanism=none
  force_use_keys:
    # separate builds for each Python
    # this duplicates libdolfinx outputs, but results in faster builds
    - python

outputs:
  - name: fenics-libdolfinx
    script: build-libdolfinx.sh  # [not win]
    script: build-libdolfinx.bat  # [win]
    build:
      skip_compile_pyc:
        - '*'  # [build_platform != target_platform]
      run_exports:
        - {{ pin_subpackage("fenics-libdolfinx", max_pin="x.x.x") }}
        - petsc * {{ scalar }}_*  # [not win]
      ignore_run_exports_from:
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      force_use_keys:
        - python
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - make  # [not win]
        - ninja  # [win]
        - pkg-config  # [not win]
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi | replace("impi", "impi-devel") }}
        - libadios2  # [not win]
        - libadios2 * mpi_{{ mpi }}_*  # [not win]
        - kahip  # [not win]
        - libboost-devel
        - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
        - parmetis  # [not win]
        - libscotch {{ scotch }}
        - libptscotch {{ scotch }}
        - petsc  # [not win]
        - petsc * {{ scalar }}_*  # [not win]
        - pugixml
        - slepc  # [not win]
        - spdlog
        - fenics-libbasix {{ major_minor }}.*
        - fenics-ufcx {{ major_minor }}.*
      run:
        # these don't have run_exports
        # but are needed at runtime for code generation
        - fenics-ufcx  {{ major_minor }}.*
        - parmetis  # [not win]
        # needs boost metadata just to CMake-load fenix-libdolfinx
        - libboost-devel
    test:
      script: test-libdolfinx.sh  # [not win]
      script: test-libdolfinx.bat  # [win]
      source_files:
        - cpp/test
      files:
        - impi-toolchain.cmake  # [win]
      requires:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - impi-devel  # [win]
        - pkg-config
        - cmake
        - catch2 3.*
        - make  # [not win]
        - ninja  # [win]
        - fenics-ffcx {{ major_minor }}.*
  - name: fenics-dolfinx
    script: build-dolfinx.sh  # [not win]
    script: build-dolfinx.bat  # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - ninja
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - nanobind                               # [build_platform != target_platform]
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi | replace("impi", "impi-devel") }}
        # hdf5 shouldn't be needed here, but solver fails without it
        - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
        - {{ pin_subpackage("fenics-libdolfinx", exact=True) }}
        - python
        - pip
        - scikit-build-core
        - wheel
        - nanobind
        - fenics-basix {{ major_minor }}.*
        - mpi4py
        - petsc * {{ scalar }}_*  # [not win]
        - petsc4py  # [not win]
        - slepc  # [not win]
        - slepc4py  # [not win]
      run_constrained:
        - {{ pin_compatible("nanobind", max_pin="x.x") }}
      run:
        # we shouldn't need to depend on compiler version,
        # but pybind11 includes compiler version in the ABI
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - pkg-config
        - python
        - {{ pin_subpackage("fenics-libdolfinx", exact=True) }}
        - cffi
        - mpi4py
        - numpy >=1.21
        - petsc4py  # [not win]
        - slepc4py  # [not win]
        - fenics-basix {{ major_minor }}.*
        - fenics-ffcx {{ major_minor }}.*
        - fenics-ufl {{ ufl_version }}.*
    test:
      script: test-dolfinx.sh  # [not win]
      script: test-dolfinx.bat  # [win]
      files:
        - test_dolfinx.py
      source_files:
        - python/demo
        - python/test
      requires:
        - pip
        - pytest >=6
        - python-gmsh
        # linux-aarch64 getting old gmsh with missing cairo
        # unclear what pin is holding it back
        - cairo  # [linux and aarch64]
        - sympy
        - scipy
        - matplotlib

about:
  home: https://fenicsproject.org
  summary: The computational environment of FEniCSx
  description: |
    DOLFINx is the computational environment of FEniCSx
    and implements the FEniCS Problem Solving Environment in Python and C++.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://docs.fenicsproject.org/dolfinx/v{{ version }}/
  dev_url: https://github.com/fenics/dolfinx

extra:
  feedstock-name: fenics-dolfinx
  recipe-maintainers:
    - minrk
