# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-15
  strategy:
    matrix:
      osx_64_mpimpichpython3.10.____cpythonscalarcomplex:
        CONFIG: osx_64_mpimpichpython3.10.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpimpichpython3.10.____cpythonsca_hd5dcb8e8
      osx_64_mpimpichpython3.10.____cpythonscalarreal:
        CONFIG: osx_64_mpimpichpython3.10.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpimpichpython3.10.____cpythonscalarreal
      osx_64_mpimpichpython3.11.____cpythonscalarcomplex:
        CONFIG: osx_64_mpimpichpython3.11.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpimpichpython3.11.____cpythonsca_hce2edf6d
      osx_64_mpimpichpython3.11.____cpythonscalarreal:
        CONFIG: osx_64_mpimpichpython3.11.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpimpichpython3.11.____cpythonscalarreal
      osx_64_mpimpichpython3.12.____cpythonscalarcomplex:
        CONFIG: osx_64_mpimpichpython3.12.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpimpichpython3.12.____cpythonsca_h498bbdcf
      osx_64_mpimpichpython3.12.____cpythonscalarreal:
        CONFIG: osx_64_mpimpichpython3.12.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpimpichpython3.12.____cpythonscalarreal
      osx_64_mpiopenmpipython3.10.____cpythonscalarcomplex:
        CONFIG: osx_64_mpiopenmpipython3.10.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpiopenmpipython3.10.____cpythons_h3248b6c8
      osx_64_mpiopenmpipython3.10.____cpythonscalarreal:
        CONFIG: osx_64_mpiopenmpipython3.10.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpiopenmpipython3.10.____cpythons_h588c2b78
      osx_64_mpiopenmpipython3.11.____cpythonscalarcomplex:
        CONFIG: osx_64_mpiopenmpipython3.11.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpiopenmpipython3.11.____cpythons_hafbfc68d
      osx_64_mpiopenmpipython3.11.____cpythonscalarreal:
        CONFIG: osx_64_mpiopenmpipython3.11.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpiopenmpipython3.11.____cpythons_h6a18a4a9
      osx_64_mpiopenmpipython3.12.____cpythonscalarcomplex:
        CONFIG: osx_64_mpiopenmpipython3.12.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpiopenmpipython3.12.____cpythons_hdf15701b
      osx_64_mpiopenmpipython3.12.____cpythonscalarreal:
        CONFIG: osx_64_mpiopenmpipython3.12.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_mpiopenmpipython3.12.____cpythons_h9cf4cb98
      osx_arm64_mpimpichpython3.10.____cpythonscalarcomplex:
        CONFIG: osx_arm64_mpimpichpython3.10.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpimpichpython3.10.____cpython_ha82255f8
      osx_arm64_mpimpichpython3.10.____cpythonscalarreal:
        CONFIG: osx_arm64_mpimpichpython3.10.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpimpichpython3.10.____cpython_h7c481527
      osx_arm64_mpimpichpython3.11.____cpythonscalarcomplex:
        CONFIG: osx_arm64_mpimpichpython3.11.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpimpichpython3.11.____cpython_ha33ed6b0
      osx_arm64_mpimpichpython3.11.____cpythonscalarreal:
        CONFIG: osx_arm64_mpimpichpython3.11.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpimpichpython3.11.____cpython_hc3fa011c
      osx_arm64_mpimpichpython3.12.____cpythonscalarcomplex:
        CONFIG: osx_arm64_mpimpichpython3.12.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpimpichpython3.12.____cpython_hd3112ea8
      osx_arm64_mpimpichpython3.12.____cpythonscalarreal:
        CONFIG: osx_arm64_mpimpichpython3.12.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpimpichpython3.12.____cpython_hb4e82c4d
      osx_arm64_mpiopenmpipython3.10.____cpythonscalarcomplex:
        CONFIG: osx_arm64_mpiopenmpipython3.10.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpiopenmpipython3.10.____cpyth_ha299e372
      osx_arm64_mpiopenmpipython3.10.____cpythonscalarreal:
        CONFIG: osx_arm64_mpiopenmpipython3.10.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpiopenmpipython3.10.____cpyth_h95734737
      osx_arm64_mpiopenmpipython3.11.____cpythonscalarcomplex:
        CONFIG: osx_arm64_mpiopenmpipython3.11.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpiopenmpipython3.11.____cpyth_h48703a1a
      osx_arm64_mpiopenmpipython3.11.____cpythonscalarreal:
        CONFIG: osx_arm64_mpiopenmpipython3.11.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpiopenmpipython3.11.____cpyth_hd087caea
      osx_arm64_mpiopenmpipython3.12.____cpythonscalarcomplex:
        CONFIG: osx_arm64_mpiopenmpipython3.12.____cpythonscalarcomplex
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpiopenmpipython3.12.____cpyth_h26e1910f
      osx_arm64_mpiopenmpipython3.12.____cpythonscalarreal:
        CONFIG: osx_arm64_mpiopenmpipython3.12.____cpythonscalarreal
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_mpiopenmpipython3.12.____cpyth_hbb100134
  timeoutInMinutes: 120
  variables: {}

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
      export remote_url=$(Build.Repository.Uri)
      export sha=$(Build.SourceVersion)
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
      export CI=azure
      export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      export CONDA_BLD_DIR=/Users/runner/miniforge3/conda-bld
      export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
      # Archive everything in CONDA_BLD_DIR except environments
      export BLD_ARTIFACT_PREFIX=conda_artifacts
      if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
        # Archive the CONDA_BLD_DIR environments only when the job fails
        export ENV_ARTIFACT_PREFIX=conda_envs
      fi
      ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)
